### ISSUE TITLE
Feature request: `arrow_shift = 1` land arrow on the surface of the node marker

### ISSUE THREAD

**Issue by hdavid16** [MakieOrg/GraphMakie.jl#101]
It would be great to be able to set the arrow shift parameter to 1 and have the tip of the arrow land on the edge (surface) of the node, not on the center of the node. This would be the preferred behavior. This will require taking into account the size of the marker.

The current work around is to pass a vector of arrow shifts to try to get them to land on the surface of each node (requires some trial and error).

**Comment by hexaeder** [comment]
I agree that this would look nice.

It is however quite hard to find the correct positions of the arrowheads a priori. The arrowheads are placed in data space, their position depends on:
- the size&shape of the node marker
- the size&shape of the error head

For triangular markes for example there is also a dependency on the direction. Additionally, the marker space is (per default) different from data space (i.e. the arrows and nodes won't get smaller and bigger if you zoom in and out of the figure). So it should also depend on
- markerspace for both arrows and node symbols and
- zoom level of axis.

In presence of curvy edges, the problem becomes trickier since the relation between position on edge and distance between node and arrow marker is non-linear.

This is why I've decided to throw the nicer aesthetics out of the window and go with markers in the center of a the edges in the first place. And tbh for me this reasoning still holds and its not worth the hassle. But maybe I am missing something and if there is a relatively straight forward way of calculating those positions!

In the mean time it might be worth investigating a function which fixes this *after the plot* (similar to your manual approach). Something like
```julia
fig, ax, p = graphplot(...)
move_arrows_to_nodes!(p)
```
Under the assumption that there are some Makie internals to calculate the intersection between arrow marker and node markers on a per edge base, this data could be used to bisect the the `arrow_shift` parameter for each edge until the markers barely touch. Obviously this brute force method is far to inefficient to become part of the "normal" `graphplot` pipeline.

**Comment by hdavid16** [comment]
Makes sense...
