### ISSUE TITLE
Question: edge indices

### ISSUE THREAD

**Issue by hdavid16** [MakieOrg/GraphMakie.jl#104]
Is there a particular reason why edges are being referenced with the integer index rather than the edge itself (or src, dst tuple)? I'm curious because Graphs.jl doesn't support indexed edges and there is some debate there on this: https://github.com/JuliaGraphs/Graphs.jl/issues/127

**Comment by hexaeder** [comment]
The real reason: I have a background in power grid simulations using `NetworkDynamics.jl`, that packages references edges by their index so that choice seemed natural, because that in its relatively easy to align colors with edge states (as in the [Stress on Truss Example](https://graph.makie.org/stable/generated/truss/)).

However, there are some real arguments on can make: Internally we often need to loop over all edges, edge properties and edge related information (such as the path representing the edge). IMO its much easier if you can just have arrays for all of that with the convention that their order matches the `edges(g)` iterator. Makes zipping, mapping and broadcasting simpler and you don't need to have the same keyset everywhere.

Eventually #89 might be nice addition for the user interface to allow to pass parameters as dicts with the `Edge` object as key.
