### ISSUE TITLE
Mixing directed and undirected edges

### ISSUE THREAD

**Issue by mschauer** [MakieOrg/GraphMakie.jl#139]
In causal inference one needs to plot graphs with partially oriented edges like so

![](https://raw.githubusercontent.com/mschauer/CausalInference.jl/master/assets/pc_graph_linear.png)

Here arrows indicate known and undirected edges unknown causal relationships. I usually represent those normal directed graphs which include both edges `x -> y` and `x <- y` for unknown causal relationships. 

I saw that GraphMakie already handles double edges internally. Is there a hope to extend it to plot them undirected and straight?

**Comment by hexaeder** [comment]
Plot them straight is the easy part, you could set `curve_distace=0` to enforce straight lines. However, the code path for the arrows does not depend on that, so this feature is not super straightforward. You're welcome to give it a shot in a PR.

However, since `graphplot` already supports all the building blocks, you could also write a function `prepare_arguments(g)` which generates the necessary kw arguments on the fly:

```julia
using GLMakie, GraphMakie, NetworkLayout, Graphs

g = SimpleDiGraph(5)
add_edge!(g, 1, 2)
add_edge!(g, 2, 1)
add_edge!(g, 1, 3)
add_edge!(g, 3, 1)
add_edge!(g, 2, 4)
add_edge!(g, 3, 4)
add_edge!(g, 4, 5)

function prepare_arguments(g)
    es = collect(edges(g))
    arrow_size = Dict{Graphs.SimpleEdge{Int}, Int}()
    edge_width = Dict{Graphs.SimpleEdge{Int}, Int}()
    # consider DefaultDict if you want to change the "normal" sizes

    for e in es
        reverse(e) ∈ es || continue
        arrow_size[e] = 0 # remove arrows for double lines
        if e.dst < e.src
            edge_width[e] = 0 # set draw width of one of the double edges to 0
        end
    end
    (;curve_distance=0, arrow_size, edge_width)
end

fig, ax, p = graphplot(g; layout=Stress(), ilabels=["X", "V", "W", "Z", "S"], prepare_arguments(g)...)
hidespines!(ax); hidedecorations!(ax)
```
<img width="384" alt="grafik" src="https://github.com/MakieOrg/GraphMakie.jl/assets/35867212/7340cbe1-316e-44ae-9722-2bd0fa598b4c">

**Comment by mschauer** [comment]
Thank you! I can add that to  CausalInference without even adding a dependency https://github.com/mschauer/CausalInference.jl/pull/115
