### ISSUE TITLE
Slow start

### ISSUE THREAD

**Issue by iglesias** [MakieOrg/GraphMakie.jl#143]
Something as simple as

```julia
using Graphs, GLMakie, GraphMakie

g = erdos_renyi(10, 0.1)
graphplot(g)
```

is taking over a minute, and I came for the performance claims ;-)

What is wrong with it?

**Comment by hexaeder** [comment]
Well, you're hitting the infamous time-to-first-plot issue with Julia. Since Julia is a just-in-time compiled language, a lot of code needs to be compiled for the first run of a function. Subsequent runs will be much faster. In short, that's why most people prefer an interactive REPL base workflow (similar to a Jupyter-Notebook), where you keep your Julia session alive while changing code, updating scripts and recreate plots rather than executing full scripts with a new julia processes all the time. Here is a good general introduction for [modern julia workflows](https://modernjuliaworkflows.github.io/).

Generally, Julia 1.9 improved that a lot with improved caching of precompiled codes. So first, I would recommend using that (if you're not already doing so). With that, I get a TTFP of around 13 seconds, which is not great but not terrible...

```julia
julia> import Pkg; Pkg.activate(temp=true)
#  Activating new project at `/var/folders/cx/04cwlxl9287_ndx30k6q3n1h0000gn/T/jl_4Ofxj5`

julia> Pkg.add(["Graphs", "GLMakie", "GraphMakie"])
# this might take ages

julia> @time begin
           using Graphs, GLMakie, GraphMakie
           g = erdos_renyi(10, 0.1)
           graphplot(g)
       end
# 12.330614 seconds (36.68 M allocations: 2.129 GiB, 4.68% gc time, 49.49% compilation time: 8% of which was recompilation)
```
Subsequent runs of the same code will take less than 7 ms.

**Comment by iglesias** [comment]
Ah, understood, it is also not an specific issue of GraphMakie.

Thanks a lot for the nice explanation.
