### ISSUE TITLE
ilabels not inside nodes in 3D

### ISSUE THREAD

**Issue by kockahonza** [MakieOrg/GraphMakie.jl#192]
Pretty much as the title says, when I try to use ilabels in 3D layouts the graph works and I do get labels but they're seemingly all offset by a large amount in the z direction. Maybe I'm just not using something correctly but it at least looks like a bug, I'm attaching an image with the resulting plot.

![Example plot](https://github.com/user-attachments/assets/b48ff11f-e9b3-432d-aaea-c5fa1afd8ac7)

**Comment by hexaeder** [comment]
Ah yes, the problem is the following: the text plot is drawn before the scatter plot, because the scatter plot markersize depends on the glyph size of the ilabels. Since the node plot is defined later, its markers would overdraw the labels. To circumvent this, we translate the ilabels plot +1 in z direction

https://github.com/MakieOrg/GraphMakie.jl/blob/85d4a582cceb4b5358302cc92a7c92bcdc9dff48/src/recipes.jl#L254

which is essentially taken from the [docs](https://docs.makie.org/stable/explanations/backends/cairomakie#z-order). Not a problem in 2d but quite the problem in 3d...
So we need a better way of reordering the plots without actually touching the z coordinate.

**Comment by asinghvi17** [comment]
Hmm, maybe define a depth_shift?  But that might not work in Cairo...would have to investigate.  FerriteViz.jl does this.
