### ISSUE TITLE
3D rotation doesn't move node labels

### ISSUE THREAD

**Issue by agucova** [MakieOrg/GraphMakie.jl#27]
![image](https://user-images.githubusercontent.com/4694408/127727715-6a19f215-6f3e-4364-9127-bbb07760aaf6.png)

While plotting a 3D graph with node labels, it seems the labels won't rotate with the graph, instead staying fixed at their location. (This is under WGLMakie and Pluto with JSServe)

**Comment by hexaeder** [comment]
I am not familiar with Pluto. Is this with `offline=true` as described in the [docs](http://makie.juliaplots.org/dev/wglmakie.html)? For the update of the node label positions you'll definitly need a julia process which is connected to WGL, otherwise the update of observables won't work. Rotation will work though since the projection is allready ported to javascript.

(PS: I'm not available the next few days but will look into this in the next week)

**Comment by agucova** [comment]
This was indeed using `offline=true`. After just leaving `Page()` I do get movement of the labels, however when rotating it reacts slowly and starts to drift until it's totally out of phase with the movement.

![rotation_drift](https://user-images.githubusercontent.com/4694408/127735154-8340a3c2-0728-4e38-aa34-0c68f2df7402.gif)

When zooming in all the labels clump on the center of the graph and when zooming out they get separated enough to go outside the window.

![zoom_spacing](https://user-images.githubusercontent.com/4694408/127735170-004fad36-aa18-43dd-8b44-feab39820b90.gif)

**Comment by hexaeder** [comment]
Interesting behaviour 🤔 Thanks for the report! Can you try your example with GLMakie?

**Comment by SimonDanisch** [comment]
Interesting :D I think that's a problem in the JS camera code...

**Comment by hexaeder** [comment]
seems fixed with current versions
